### ISSUE TITLE
Would it be possible to add an audio channel setting to this?

### ISSUE THREAD

**Issue by dessalines** [dmn001/youtube_channel_archiver#3]
I have this set up on a media server, and have this script on a crontab, to pull the latest videos. But it'd also be nice to be able to do a fetch for an "audio channel"?

Maybe add a whole nother file named: `youtube-dl-audio-channels.txt`

**Comment by dmn001** [comment]
You can just make a copy of the config file and in there rename the .txt file and set it to download audio only.
