### ISSUE TITLE
Only downloading in 720p

### ISSUE THREAD

**Issue by RiskiVR** [dmn001/youtube_channel_archiver#6]
I'm currently archiving a channel that's getting deleted soon, and they are only downloading in 720p. Any way to increase resolution?

**Comment by HuzaifaPatel** [comment]
If the YouTube channel has a "uploads" playlist just use that URL and put in the following command into your shell:

`youtube-dl -f best Your_Youtube_Playlist_URL`

**Comment by RiskiVR** [comment]
This helped, thank you very much!
